replicaCount: 1

app:
  sleepTime: 12
  getBatchesEndpoint: some.service/backend/qs/getBatches

image:
  repository: ghcr.io/wbstack/queryservice-updater
  tag: 0.3.84_3.4
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: "10m"
    memory: "100Mi"
  limits:
    cpu: "100m"
    memory: "200Mi"

nodeSelector: {}

tolerations: []

affinity: {}
