replicaCount:
  backend: 1
  web: 1
  webapi: 1
  alpha: 0

image:
  repository: ghcr.io/wbstack/mediawiki
  tag:
    web: 1.35-7.3-20201211-0
    webapi: 1.35-7.3-20201211-0
    backend: 1.35-7.3-20201211-0
    alpha: 1.35-7.3-20201211-0
  pullPolicy: IfNotPresent

mw:
  db:
    master: someHostName
    replica: someHostName
  redis:
    readServer: someRedisOtherServer
    writeServer: someRedisServer
    password: abc123
  mailgun:
    apikey: 1234567
    domain: somedomain.name
  recaptcha:
    sitekey: foo
    secretkey: foo
  platform:
    apiBackendHost: someHost

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

resources:
  web: {}
  webapi: {}
  alpha: {}
  backend: {}

nodeSelector: {}

tolerations: []
