repoUrls:
  deploy: https://github.com/wmde/wbaas-deploy
  wbstack: https://deer-wmde.github.io/debug-charts
clusterUrl: https://kubernetes.default.svc
environment: production

chartVersions:
  wbaasUi: 0.4.0
  wbaasApi: 0.32.1
  redis: 17.3.8
  redis2: 19.6.4
# "inherits" values from argocd-config chart
