apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "queryservice-updater.fullname" . }}
  labels:
{{ include "queryservice-updater.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "queryservice-updater.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "queryservice-updater.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HEAP_SIZE
              value: {{ .Values.app.heapSize }}
            - name: WBSTACK_LOOP_LIMIT
              value: {{ .Values.app.loopLimit| quote }}
            - name: EXTRA_JVM_OPTS
              value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAM=60m -XX:+UseSerialGC -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
            - name: GC_LOGS
              value: " "
            - name: WBSTACK_BATCH_SLEEP
              value: {{ .Values.app.sleepTime| quote }}
            - name: WBSTACK_API_ENDPOINT
              value: {{ .Values.app.getBatchesEndpoint | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
