apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-apps-ingress-{{ .Values.ingressNameSuffix }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .Values.forceSSL | quote }}
spec:
  rules:
  - host: {{ .Values.ingressHost | quote }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: platform-nginx
              port:
                number: 8080
  {{ if .Values.tls }}
  tls:
  - hosts:
    - {{ .Values.ingressHost | quote }}
    secretName: {{ .Values.ingressNameSuffix }}-tls
  {{- end }}