replicaCount: 1

image:
  repository: ghcr.io/wbstack/ui
  tag: "3.1"
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

ui:
  name: Wbstack
  url: https://www.wbstack.com
  domain: wbstack.com
  cnameRecord: sites-1.dyna.wbstack.com
  sourceLink: https://www.github.com/wbstack
  docsLink: https://wbstack.github.io/docs/
  recaptchaSitekeySecretName: ""
  recaptchaSitekeySecretKey: ""
  apiUrl: ""
  subdomainSuffix: ""

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []
