replicaCount: 1

image:
  repository: ghcr.io/wbstack/ui
  tag: "3.3"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ui:
  recaptchaSitekeySecretName: ""
  recaptchaSitekeySecretKey: ""
  apiUrl: ""
  subdomainSuffix: ""
  cnameRecord: ""

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []
