replicaCount: 1

image:
  repository: ghcr.io/deer-wmde/wbaas-ui
  tag: "sha-173df0d"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ui:
  recaptchaSitekeySecretName: ""
  recaptchaSitekeySecretKey: ""
  apiUrl: ""
  subdomainSuffix: ""
  cnameConfigMapKey: ""
  configMapName: ""

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

podLabels: {}
