apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediawiki.fullname" . }}-app-alpha
  labels:
{{ include "mediawiki.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "mediawiki.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app-alpha
